services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_farmacia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${SQL_PASSWORD}"
      MYSQL_DATABASE: "db_farmacia"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 45s

  api:
    build:
      context: ./ControlFarmacia.API
      dockerfile: Dockerfile
    container_name: api_farmacia_container
    ports:
      - "5256:80"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
      DB_CONNECTION: "${DB_CONNECTION}"
      JWT_KEY: "${JWT_KEY}"
    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  mysql_data: